name: cashflow
description: "CashFlow is an easy-to-use expense tracker that helps manage finances, categorize transactions, and visualize spending through charts."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.0   # A SQLite database library with type-safe queries
  sqflite: ^2.0.0+4   # SQLite plugin for local storage
  path_provider: ^2.0.14   # Get commonly used locations for storing files
  path: ^1.8.3   # Manipulate file paths (cross-platform)

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.0   #Code generator for Floor (used to create DB entities and DAOs)
  build_runner: ^2.4.6   # to generate code (for Floor, etc.)


  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vector.png